remote_theme: tuur29/pages-themes-cayman

show_downloads: true
darkmode: true
hide_first_title: false 
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: https://github.com//Duui3111/BetterTaskBar/releases/download/1.60.8/BetterTaskbar.exe
      zip_title: Download
      zip_hide: false
      tar_url: https://github.com/Duui3111/BetterTaskBar/zipball/main
      tar_title: Download .zip
      tar_hide: false
      github_hide: false