remote_theme: Duui3111/MMJ-github-pages

Buttons:
 btn1_text: View on GitHub
 btn1_url: https://github.com/Duui3111/BetterTaskBar
 btn2_text: Download
 bt2_url: https://github.com//Duui3111/BetterTaskBar/releases/download/1.60.8/BetterTaskbar.exe
 btn3_text: Download .zip
 btn3_url: https://github.com/Duui3111/BetterTaskBar/zipball/main