remote_theme: tuur29/pages-themes-cayman

show_downloads: true
darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: false
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: false
      github_hide: false