remote_theme: Duui3111/MMJ-github-pages

title: Better TaskBar

author:
 url: https://github.com/Duui3111/
 name: Duui3111

Buttons:
 btn1_text: View on GitHub
 btn1_url: https://github.com/Duui3111/BetterTaskBar
 btn2_text: Download
 btn2_url: https://github.com/Duui3111/BetterTaskBar/releases/latest/download/BetterTaskbar.exe
 btn3_text: Download .zip
 btn3_url: https://github.com/Duui3111/BetterTaskBar/zipball/main



